# Generated by Django 5.0.4 on 2024-05-21 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_is_deleted_story_soft_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='story',
            name='soft_deleted_at',
        ),
        migrations.AddField(
            model_name='story',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_stories', to=settings.AUTH_USER_MODEL),
        ),
    ]
