# Generated by Django 5.0.4 on 2024-05-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='created_at',
            new_name='date_created',
        ),
    ]
