# Generated by Django 5.0.4 on 2024-05-26 06:01

import apps.chats.models.chat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rename_created_at_chat_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.chats.models.chat.chat_image_directory_path),
        ),
    ]
