# Generated by Django 5.0.4 on 2024-04-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_active',
        ),
        migrations.AddField(
            model_name='chat',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
