# Generated by Django 5.0.4 on 2024-04-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chat_creator_alter_chat_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='description',
            field=models.TextField(blank=True, default='description'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(default='default title', max_length=255),
        ),
    ]
