# Generated by Django 5.0.4 on 2024-06-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
