# Generated by Django 5.0.4 on 2024-06-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_message_date_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
