# Generated by Django 5.0.4 on 2024-05-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chat_description_alter_chat_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='date_sent',
        ),
        migrations.AddField(
            model_name='message',
            name='date_last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
