# Generated by Django 5.0.4 on 2024-06-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_remove_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='message',
            name='date_seen',
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
