# Generated by Django 5.0.4 on 2024-06-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_remove_chat_is_active_remove_message_date_seen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
