# Generated by Django 5.0.4 on 2024-06-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_remove_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
