# Generated by Django 5.0.4 on 2024-05-09 15:40

import apps.users.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/images/profile_images/default_profile_image.png', upload_to=apps.users.models.profile.user_directory_path),
        ),
    ]
