# Generated by Django 5.0.4 on 2024-05-10 05:53

import apps.users.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/images/default_profile_image.jpg', upload_to=apps.users.models.profile.user_directory_path),
        ),
    ]
