# Generated by Django 5.0.4 on 2024-06-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_saved_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='edited',
            new_name='is_edited',
        ),
    ]
