# Generated by Django 5.0.4 on 2024-05-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_created_at_notification_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date_created',
            new_name='date_sent',
        ),
    ]
